import {
  Flame,
  Dumbbell,
  Utensils,
  BookOpen,
  Newspaper,
  Moon,
  Plus,
  Check,
  CalendarDays,
  Snowflake,
  AlertTriangle,
  CheckCircle2,
  AlertCircle,
  PartyPopper,
  Headphones,
  Bookmark,
  BookmarkPlus,
  Menu,
  Trophy,
  ChevronRight,
  Sun,
  Moon as MoonIcon,
  Smartphone,
  Tablet,
  Monitor,
  type LucideIcon,
} from 'lucide-react'

export const icons = {
  flame: Flame,
  exercise: Dumbbell,
  restaurant: Utensils,
  menu_book: BookOpen,
  newspaper: Newspaper,
  bedtime: Moon,
  add: Plus,
  check: Check,
  calendar: CalendarDays,
  snowflake: Snowflake,
  warning: AlertTriangle,
  check_circle: CheckCircle2,
  error: AlertCircle,
  celebration: PartyPopper,
  headphones: Headphones,
  bookmark: Bookmark,
  bookmark_add: BookmarkPlus,
  menu: Menu,
  trophy: Trophy,
  chevron_right: ChevronRight,
  sun: Sun,
  moon: MoonIcon,
  phone: Smartphone,
  tablet: Tablet,
  monitor: Monitor,
} satisfies Record<string, LucideIcon>

export type IconName = keyof typeof icons
